//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFExercise.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WebService.CompositeType GetDataUsingDataContract(WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebService.CompositeType> GetDataUsingDataContractAsync(WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHeight", ReplyAction="http://tempuri.org/IService1/GetHeightResponse")]
        WebService.Response.HeightResponse GetHeight(WebService.Request.GetHeightRequest heightRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHeight", ReplyAction="http://tempuri.org/IService1/GetHeightResponse")]
        System.Threading.Tasks.Task<WebService.Response.HeightResponse> GetHeightAsync(WebService.Request.GetHeightRequest heightRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWeight", ReplyAction="http://tempuri.org/IService1/GetWeightResponse")]
        WebService.Response.WeightResponse GetWeight(WebService.Request.GetWeightRequest weightRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWeight", ReplyAction="http://tempuri.org/IService1/GetWeightResponse")]
        System.Threading.Tasks.Task<WebService.Response.WeightResponse> GetWeightAsync(WebService.Request.GetWeightRequest weightRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateBMI", ReplyAction="http://tempuri.org/IService1/CalculateBMIResponse")]
        WebService.Response.CalculateBMIResponse CalculateBMI(WebService.Request.BMIConversionRequest BMIRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateBMI", ReplyAction="http://tempuri.org/IService1/CalculateBMIResponse")]
        System.Threading.Tasks.Task<WebService.Response.CalculateBMIResponse> CalculateBMIAsync(WebService.Request.BMIConversionRequest BMIRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCFExercise.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFExercise.ServiceReference2.IService1>, WCFExercise.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebService.CompositeType GetDataUsingDataContract(WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WebService.CompositeType> GetDataUsingDataContractAsync(WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WebService.Response.HeightResponse GetHeight(WebService.Request.GetHeightRequest heightRequest) {
            return base.Channel.GetHeight(heightRequest);
        }
        
        public System.Threading.Tasks.Task<WebService.Response.HeightResponse> GetHeightAsync(WebService.Request.GetHeightRequest heightRequest) {
            return base.Channel.GetHeightAsync(heightRequest);
        }
        
        public WebService.Response.WeightResponse GetWeight(WebService.Request.GetWeightRequest weightRequest) {
            return base.Channel.GetWeight(weightRequest);
        }
        
        public System.Threading.Tasks.Task<WebService.Response.WeightResponse> GetWeightAsync(WebService.Request.GetWeightRequest weightRequest) {
            return base.Channel.GetWeightAsync(weightRequest);
        }
        
        public WebService.Response.CalculateBMIResponse CalculateBMI(WebService.Request.BMIConversionRequest BMIRequest) {
            return base.Channel.CalculateBMI(BMIRequest);
        }
        
        public System.Threading.Tasks.Task<WebService.Response.CalculateBMIResponse> CalculateBMIAsync(WebService.Request.BMIConversionRequest BMIRequest) {
            return base.Channel.CalculateBMIAsync(BMIRequest);
        }
    }
}
