//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_CommuterWazeWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferredRoute
    {
        public int PreferredRouteID { get; set; }
        public int RouteID { get; set; }
        public string Username { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
