//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommuterWazeWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommuterWazeDatabaseEntities : DbContext
    {
        public CommuterWazeDatabaseEntities()
            : base("name=CommuterWazeDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PreferredRoute> PreferredRoutes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
