//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebApp.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeWebService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeeWebApp.EmployeeService.EmployeeRequest))]
    public partial class EmployeeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeRequest", Namespace="http://schemas.datacontract.org/2004/07/EmployeeWebService")]
    [System.SerializableAttribute()]
    public partial class EmployeeRequest : EmployeeWebApp.EmployeeService.EmployeeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/EmployeeWebService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeeWebApp.EmployeeService.EmployeeResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeWebApp.EmployeeService.EmployeeDetails EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeWebApp.EmployeeService.EmployeeDetails Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeResponse", Namespace="http://schemas.datacontract.org/2004/07/EmployeeWebService")]
    [System.SerializableAttribute()]
    public partial class EmployeeResponse : EmployeeWebApp.EmployeeService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEmployee", ReplyAction="http://tempuri.org/IService1/CreateEmployeeResponse")]
        EmployeeWebApp.EmployeeService.EmployeeResponse CreateEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEmployee", ReplyAction="http://tempuri.org/IService1/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> CreateEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllEmployee", ReplyAction="http://tempuri.org/IService1/ReadAllEmployeeResponse")]
        EmployeeWebApp.EmployeeService.EmployeeResponse[] ReadAllEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllEmployee", ReplyAction="http://tempuri.org/IService1/ReadAllEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse[]> ReadAllEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadSpecificEmployee", ReplyAction="http://tempuri.org/IService1/ReadSpecificEmployeeResponse")]
        EmployeeWebApp.EmployeeService.EmployeeResponse ReadSpecificEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadSpecificEmployee", ReplyAction="http://tempuri.org/IService1/ReadSpecificEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> ReadSpecificEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployee", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeResponse")]
        EmployeeWebApp.EmployeeService.EmployeeResponse UpdateEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployee", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> UpdateEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        EmployeeWebApp.EmployeeService.EmployeeResponse DeleteEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> DeleteEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : EmployeeWebApp.EmployeeService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<EmployeeWebApp.EmployeeService.IService1>, EmployeeWebApp.EmployeeService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmployeeWebApp.EmployeeService.EmployeeResponse CreateEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> CreateEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public EmployeeWebApp.EmployeeService.EmployeeResponse[] ReadAllEmployee() {
            return base.Channel.ReadAllEmployee();
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse[]> ReadAllEmployeeAsync() {
            return base.Channel.ReadAllEmployeeAsync();
        }
        
        public EmployeeWebApp.EmployeeService.EmployeeResponse ReadSpecificEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.ReadSpecificEmployee(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> ReadSpecificEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.ReadSpecificEmployeeAsync(request);
        }
        
        public EmployeeWebApp.EmployeeService.EmployeeResponse UpdateEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> UpdateEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public EmployeeWebApp.EmployeeService.EmployeeResponse DeleteEmployee(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApp.EmployeeService.EmployeeResponse> DeleteEmployeeAsync(EmployeeWebApp.EmployeeService.EmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
    }
}
