//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2ndExercise.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1._4InputsServiceSoap")]
    public interface _4InputsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddFourInputs", ReplyAction="*")]
        int AddFourInputs(int input1, int input2, int input3, int input4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddFourInputs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddFourInputsAsync(int input1, int input2, int input3, int input4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AverageFourInputs", ReplyAction="*")]
        int AverageFourInputs(int input1, int input2, int input3, int input4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AverageFourInputs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AverageFourInputsAsync(int input1, int input2, int input3, int input4);
        
        // CODEGEN: Generating message contract since element name SwapFourInputsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SwapFourInputs", ReplyAction="*")]
        _2ndExercise.ServiceReference1.SwapFourInputsResponse SwapFourInputs(_2ndExercise.ServiceReference1.SwapFourInputsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SwapFourInputs", ReplyAction="*")]
        System.Threading.Tasks.Task<_2ndExercise.ServiceReference1.SwapFourInputsResponse> SwapFourInputsAsync(_2ndExercise.ServiceReference1.SwapFourInputsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SwapFourInputsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SwapFourInputs", Namespace="http://tempuri.org/", Order=0)]
        public _2ndExercise.ServiceReference1.SwapFourInputsRequestBody Body;
        
        public SwapFourInputsRequest() {
        }
        
        public SwapFourInputsRequest(_2ndExercise.ServiceReference1.SwapFourInputsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SwapFourInputsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int input2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int input3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int input4;
        
        public SwapFourInputsRequestBody() {
        }
        
        public SwapFourInputsRequestBody(int input1, int input2, int input3, int input4) {
            this.input1 = input1;
            this.input2 = input2;
            this.input3 = input3;
            this.input4 = input4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SwapFourInputsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SwapFourInputsResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2ndExercise.ServiceReference1.SwapFourInputsResponseBody Body;
        
        public SwapFourInputsResponse() {
        }
        
        public SwapFourInputsResponse(_2ndExercise.ServiceReference1.SwapFourInputsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SwapFourInputsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2ndExercise.ServiceReference1.ArrayOfInt SwapFourInputsResult;
        
        public SwapFourInputsResponseBody() {
        }
        
        public SwapFourInputsResponseBody(_2ndExercise.ServiceReference1.ArrayOfInt SwapFourInputsResult) {
            this.SwapFourInputsResult = SwapFourInputsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface _4InputsServiceSoapChannel : _2ndExercise.ServiceReference1._4InputsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class _4InputsServiceSoapClient : System.ServiceModel.ClientBase<_2ndExercise.ServiceReference1._4InputsServiceSoap>, _2ndExercise.ServiceReference1._4InputsServiceSoap {
        
        public _4InputsServiceSoapClient() {
        }
        
        public _4InputsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public _4InputsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public _4InputsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public _4InputsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddFourInputs(int input1, int input2, int input3, int input4) {
            return base.Channel.AddFourInputs(input1, input2, input3, input4);
        }
        
        public System.Threading.Tasks.Task<int> AddFourInputsAsync(int input1, int input2, int input3, int input4) {
            return base.Channel.AddFourInputsAsync(input1, input2, input3, input4);
        }
        
        public int AverageFourInputs(int input1, int input2, int input3, int input4) {
            return base.Channel.AverageFourInputs(input1, input2, input3, input4);
        }
        
        public System.Threading.Tasks.Task<int> AverageFourInputsAsync(int input1, int input2, int input3, int input4) {
            return base.Channel.AverageFourInputsAsync(input1, input2, input3, input4);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2ndExercise.ServiceReference1.SwapFourInputsResponse _2ndExercise.ServiceReference1._4InputsServiceSoap.SwapFourInputs(_2ndExercise.ServiceReference1.SwapFourInputsRequest request) {
            return base.Channel.SwapFourInputs(request);
        }
        
        public _2ndExercise.ServiceReference1.ArrayOfInt SwapFourInputs(int input1, int input2, int input3, int input4) {
            _2ndExercise.ServiceReference1.SwapFourInputsRequest inValue = new _2ndExercise.ServiceReference1.SwapFourInputsRequest();
            inValue.Body = new _2ndExercise.ServiceReference1.SwapFourInputsRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            inValue.Body.input3 = input3;
            inValue.Body.input4 = input4;
            _2ndExercise.ServiceReference1.SwapFourInputsResponse retVal = ((_2ndExercise.ServiceReference1._4InputsServiceSoap)(this)).SwapFourInputs(inValue);
            return retVal.Body.SwapFourInputsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2ndExercise.ServiceReference1.SwapFourInputsResponse> _2ndExercise.ServiceReference1._4InputsServiceSoap.SwapFourInputsAsync(_2ndExercise.ServiceReference1.SwapFourInputsRequest request) {
            return base.Channel.SwapFourInputsAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2ndExercise.ServiceReference1.SwapFourInputsResponse> SwapFourInputsAsync(int input1, int input2, int input3, int input4) {
            _2ndExercise.ServiceReference1.SwapFourInputsRequest inValue = new _2ndExercise.ServiceReference1.SwapFourInputsRequest();
            inValue.Body = new _2ndExercise.ServiceReference1.SwapFourInputsRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            inValue.Body.input3 = input3;
            inValue.Body.input4 = input4;
            return ((_2ndExercise.ServiceReference1._4InputsServiceSoap)(this)).SwapFourInputsAsync(inValue);
        }
    }
}
