//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserCredentialEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public string User { get; set; }
        public string Salt { get; set; }
        public string Hash { get; set; }
    }
}
